#!/usr/bin/env python3
"""
Qwen3.5 module pipeline code generator.

Step-2 覆盖范围：
1) 输入支持 raw Python 或 GitHub HTML 快照（自动恢复 rawLines）
2) 生成 Module GenAI YAML（GPU 版本 + CPU compare 版本）
3) 生成模块骨架 hpp/cpp
4) 生成 Python reference bridge 与 compare 脚本（CPU 对齐）
"""

from __future__ import annotations

import argparse
import ast
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

DEFAULT_DEVICES = {
    "pipeline_params": "CPU",
    "image_preprocessor": "GPU",
    "prompt_encoder": "CPU",
    "text_embedding": "GPU",
    "vision_encoder": "GPU",
    "embedding_merger": "GPU",
    "llm_inference": "GPU",
    "pipeline_result": "CPU",
}


@dataclass
class ModelAnalysis:
    class_names: List[str]
    function_names: List[str]
    found_signals: Dict[str, bool]
    notes: List[str]
    source_mode: str
    recovered_source_file: str | None


def _looks_like_html(text: str) -> bool:
    head = text[:6000].lower()
    return "<!doctype html" in head or "<html" in head


def _extract_raw_lines_json_array(text: str) -> List[str]:
    m = re.search(r'"rawLines"\s*:\s*(\[.*?\])\s*,\s*"stylingDirectives"', text, re.DOTALL)
    if not m:
        raise RuntimeError("未在 HTML 中找到 rawLines 字段，无法恢复 Python 源码。")

    raw_lines_literal = m.group(1)
    try:
        raw_lines = json.loads(raw_lines_literal)
    except json.JSONDecodeError as e:
        raise RuntimeError(f"解析 rawLines 失败: {e}") from e

    if not isinstance(raw_lines, list) or not raw_lines or not all(isinstance(x, str) for x in raw_lines):
        raise RuntimeError("rawLines 字段格式异常。")

    return raw_lines


def load_python_source(input_file: Path, recovered_output_file: Path | None = None) -> Tuple[str, str, Path | None]:
    raw_text = input_file.read_text(encoding="utf-8", errors="ignore")

    if not _looks_like_html(raw_text):
        return raw_text, "python", None

    raw_lines = _extract_raw_lines_json_array(raw_text)
    recovered_text = "\n".join(raw_lines) + "\n"

    recovered_path = recovered_output_file
    if recovered_path is not None:
        recovered_path.parent.mkdir(parents=True, exist_ok=True)
        recovered_path.write_text(recovered_text, encoding="utf-8")

    return recovered_text, "html_rawlines", recovered_path


def analyze_python_model(py_file: Path, recovered_output_file: Path | None = None) -> ModelAnalysis:
    src, source_mode, recovered_file = load_python_source(py_file, recovered_output_file)

    class_names: List[str] = []
    function_names: List[str] = []

    try:
        tree = ast.parse(src)
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                class_names.append(node.name)
            elif isinstance(node, ast.FunctionDef):
                function_names.append(node.name)
    except SyntaxError:
        pass

    lowered = src.lower()
    found_signals = {
        "qwen3_5_conditional_generation": "qwen3_5forconditionalgeneration" in lowered,
        "qwen3_5_model": "class qwen3_5model" in lowered,
        "vision_model": "class qwen3_5visionmodel" in lowered,
        "text_model": "class qwen3_5textmodel" in lowered,
        "image_features": "get_image_features" in lowered or "pixel_values" in lowered,
        "video_features": "get_video_features" in lowered or "pixel_values_videos" in lowered,
        "rope_index": "get_rope_index" in lowered,
        "rope_deltas": "rope_deltas" in lowered,
        "embed_merge": "masked_scatter" in lowered or "inputs_embeds" in lowered,
        "language_model": "language_model" in lowered,
        "linear_attention": "linear_attention" in lowered or "gateddeltanet" in lowered,
    }

    notes: List[str] = []
    if found_signals["qwen3_5_conditional_generation"]:
        notes.append("检测到 Qwen3.5 条件生成主类，可映射主 pipeline。")
    if found_signals["vision_model"]:
        notes.append("检测到视觉主干，可映射 VisionEncoder。")
    if found_signals["rope_index"] or found_signals["rope_deltas"]:
        notes.append("检测到 RoPE index/delta 逻辑，可映射 VisionEncoder -> LLMInference。")
    if found_signals["video_features"]:
        notes.append("检测到视频分支，YAML 保留 video_embedding 端口。")
    if found_signals["linear_attention"]:
        notes.append("检测到线性注意力路径，CPU 对齐阶段注意 cache 行为。")

    return ModelAnalysis(
        class_names=sorted(set(class_names)),
        function_names=sorted(set(function_names)),
        found_signals=found_signals,
        notes=notes,
        source_mode=source_mode,
        recovered_source_file=str(recovered_file) if recovered_file else None,
    )


def build_yaml_content(model_dir: str, devices: Dict[str, str], cpu_compare: bool) -> str:
    d = {k: ("CPU" if cpu_compare else v) for k, v in devices.items()}

    lines = [
        "# Auto-generated by tools/module_genai/qwen3_5_codegen.py",
        "global_context:",
        "  model_type: \"qwen3_5\"",
        "",
        "pipeline_modules:",
        "  pipeline_params:",
        "    type: \"ParameterModule\"",
        "    outputs:",
        "      - name: \"image\"",
        "        type: \"OVTensor\"",
        "      - name: \"prompt\"",
        "        type: \"String\"",
        "",
        "  image_preprocessor:",
        "    type: \"ImagePreprocessModule\"",
        f"    device: \"{d['image_preprocessor']}\"",
        "    inputs:",
        "      - name: \"image\"",
        "        type: \"OVTensor\"",
        "        source: \"pipeline_params.image\"",
        "    outputs:",
        "      - name: \"raw_data\"",
        "        type: \"OVTensor\"",
        "      - name: \"source_size\"",
        "        type: \"VecInt\"",
        "    params:",
        f"      model_path: \"{model_dir}\"",
        "",
        "  prompt_encoder:",
        "    type: \"TextEncoderModule\"",
        f"    device: \"{d['prompt_encoder']}\"",
        "    inputs:",
        "      - name: \"prompt\"",
        "        type: \"String\"",
        "        source: \"pipeline_params.prompt\"",
        "      - name: \"encoded_image\"",
        "        type: \"OVTensor\"",
        "        source: \"image_preprocessor.raw_data\"",
        "      - name: \"source_size\"",
        "        type: \"VecInt\"",
        "        source: \"image_preprocessor.source_size\"",
        "    outputs:",
        "      - name: \"input_ids\"",
        "        type: \"OVTensor\"",
        "      - name: \"mask\"",
        "        type: \"OVTensor\"",
        "      - name: \"images_sequence\"",
        "        type: \"VecInt\"",
        "    params:",
        f"      model_path: \"{model_dir}\"",
        "",
        "  text_embedding:",
        "    type: \"TextEmbeddingModule\"",
        f"    device: \"{d['text_embedding']}\"",
        "    inputs:",
        "      - name: \"input_ids\"",
        "        type: \"OVTensor\"",
        "        source: \"prompt_encoder.input_ids\"",
        "    outputs:",
        "      - name: \"input_embedding\"",
        "        type: \"OVTensor\"",
        "    params:",
        f"      model_path: \"{model_dir}\"",
        "      scale_emb: \"1.0\"",
        "",
        "  vision_encoder:",
        "    type: \"VisionEncoderModule\"",
        f"    device: \"{d['vision_encoder']}\"",
        "    inputs:",
        "      - name: \"preprocessed_image\"",
        "        type: \"OVTensor\"",
        "        source: \"image_preprocessor.raw_data\"",
        "      - name: \"source_size\"",
        "        type: \"VecInt\"",
        "        source: \"image_preprocessor.source_size\"",
        "      - name: \"images_sequence\"",
        "        type: \"VecInt\"",
        "        source: \"prompt_encoder.images_sequence\"",
        "      - name: \"input_ids\"",
        "        type: \"OVTensor\"",
        "        source: \"prompt_encoder.input_ids\"",
        "    outputs:",
        "      - name: \"image_embedding\"",
        "        type: \"OVTensor\"",
        "      - name: \"video_embedding\"",
        "        type: \"OVTensor\"",
        "      - name: \"position_ids\"",
        "        type: \"OVTensor\"",
        "      - name: \"rope_delta\"",
        "        type: \"Int\"",
        "    params:",
        f"      model_path: \"{model_dir}\"",
        "      vision_start_token_id: 151652",
        "",
        "  embedding_merger:",
        "    type: \"EmbeddingMergerModule\"",
        f"    device: \"{d['embedding_merger']}\"",
        "    inputs:",
        "      - name: \"input_ids\"",
        "        type: \"OVTensor\"",
        "        source: \"prompt_encoder.input_ids\"",
        "      - name: \"input_embedding\"",
        "        type: \"OVTensor\"",
        "        source: \"text_embedding.input_embedding\"",
        "      - name: \"image_embedding\"",
        "        type: \"OVTensor\"",
        "        source: \"vision_encoder.image_embedding\"",
        "      - name: \"video_embedding\"",
        "        type: \"OVTensor\"",
        "        source: \"vision_encoder.video_embedding\"",
        "    outputs:",
        "      - name: \"merged_embedding\"",
        "        type: \"OVTensor\"",
        "    params:",
        f"      model_path: \"{model_dir}\"",
        "",
        "  llm_inference:",
        "    type: \"LLMInferenceModule\"",
        f"    device: \"{d['llm_inference']}\"",
        "    inputs:",
        "      - name: \"embeds\"",
        "        type: \"OVTensor\"",
        "        source: \"embedding_merger.merged_embedding\"",
        "      - name: \"position_ids\"",
        "        type: \"OVTensor\"",
        "        source: \"vision_encoder.position_ids\"",
        "      - name: \"rope_delta\"",
        "        type: \"Int\"",
        "        source: \"vision_encoder.rope_delta\"",
        "    outputs:",
        "      - name: \"generated_text\"",
        "        type: \"String\"",
        "    params:",
        f"      model_path: \"{model_dir}\"",
        "      max_new_tokens: \"16\"",
        "      do_sample: \"false\"",
        "      top_p: \"1.0\"",
        "      top_k: \"50\"",
        "      temperature: \"1.0\"",
        "      repetition_penalty: \"1.0\"",
        "",
        "  pipeline_result:",
        "    type: \"ResultModule\"",
        "    inputs:",
        "      - name: \"generated_text\"",
        "        type: \"String\"",
        "        source: \"llm_inference.generated_text\"",
        "",
    ]
    return "\n".join(lines)


def _camel_case(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def generate_module_skeleton(module_name: str, device: str) -> Tuple[str, str, str]:
    cls = f"Generated{_camel_case(module_name)}Module"
    file_base = f"md_generated_{module_name}"

    hpp = f'''// Auto-generated skeleton
#pragma once

#include "module_genai/module.hpp"
#include "module_genai/module_type.hpp"

namespace ov {{
namespace genai {{
namespace module {{

class {cls} : public IBaseModule {{
    DeclareModuleConstructor({cls});

private:
    bool initialize();
    void run_with_python_reference();
}};

REGISTER_MODULE_CONFIG({cls});

}}  // namespace module
}}  // namespace genai
}}  // namespace ov
'''

    cpp = f'''// Auto-generated skeleton
#include "{file_base}.hpp"

#include "module_genai/module_factory.hpp"
#include <cstdlib>

namespace ov {{
namespace genai {{
namespace module {{

GENAI_REGISTER_MODULE_SAME({cls});

void {cls}::print_static_config() {{
    std::cout << R"(
  {module_name}:
    type: "{cls}"
    device: "{device}"
    # TODO: declare inputs/outputs/params
    )" << std::endl;
}}

{cls}::{cls}(const IBaseModuleDesc::PTR& desc, const PipelineDesc::PTR& pipeline_desc)
    : IBaseModule(desc, pipeline_desc) {{
    if (!initialize()) {{
        GENAI_ERR("Failed to initialize {cls}");
    }}
}}

{cls}::~{cls}() {{}}

bool {cls}::initialize() {{
    return true;
}}

void {cls}::run_with_python_reference() {{
    // GPU阶段建议：通过 Python 原始实现做对齐。
    // TODO: 使用 pybind11 或 subprocess + 文件交换实现 I/O 映射。
    // 示例：std::system("python3 qwen3_5_reference_bridge.py --stage {module_name}");
}}

void {cls}::run() {{
    GENAI_INFO("Running module: " + module_desc->name);
    prepare_inputs();

    if (module_desc->device == "GPU") {{
        run_with_python_reference();
        return;
    }}

    // TODO: 在此填充 CPU 参考实现。
}}

}}  // namespace module
}}  // namespace genai
}}  // namespace ov
'''

    return file_base, hpp, cpp


def build_reference_bridge_script() -> str:
    return '''#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch
from PIL import Image
from transformers import AutoProcessor, Qwen3_5ForConditionalGeneration


def load_image(path: str):
    return Image.open(path).convert("RGB")


def run_full_generate(model_id_or_path: str, prompt: str, image_path: str, max_new_tokens: int = 16):
    device = torch.device("cpu")
    model = Qwen3_5ForConditionalGeneration.from_pretrained(model_id_or_path, torch_dtype=torch.float32)
    model.to(device)
    model.eval()
    processor = AutoProcessor.from_pretrained(model_id_or_path)

    messages = [{
        "role": "user",
        "content": [
            {"type": "image", "image": load_image(image_path)},
            {"type": "text", "text": prompt},
        ],
    }]

    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = processor(text=[text], images=[load_image(image_path)], return_tensors="pt")
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        out = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False)

    generated_ids = out[0][inputs["input_ids"].shape[1]:]
    decoded = processor.decode(generated_ids, skip_special_tokens=True)
    return decoded


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--stage", default="llm_full", choices=["llm_full"])
    parser.add_argument("--model", required=True, help="HF model id or local path")
    parser.add_argument("--prompt", required=True)
    parser.add_argument("--image", required=True)
    parser.add_argument("--max-new-tokens", type=int, default=16)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    result = {
        "stage": args.stage,
        "generated_text": run_full_generate(args.model, args.prompt, args.image, args.max_new_tokens),
    }
    Path(args.out).write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
'''


def build_compare_script() -> str:
    return '''#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image
from openvino import Tensor
import openvino_genai


def load_image_as_ov_tensor(image_path: str) -> Tensor:
    img = Image.open(image_path).convert("RGB")
    arr = np.array(img, dtype=np.uint8)
    if arr.ndim == 3:
        arr = np.expand_dims(arr, axis=0)
    return Tensor(arr)


def norm_text(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"\\s+", " ", s)
    return s


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--yaml", required=True)
    parser.add_argument("--python-bridge", required=True)
    parser.add_argument("--hf-model", required=True, help="Qwen3.5 HF model id or local path")
    parser.add_argument("--prompt", required=True)
    parser.add_argument("--image", required=True)
    parser.add_argument("--max-new-tokens", type=int, default=16)
    parser.add_argument("--report", required=True)
    args = parser.parse_args()

    pipe = openvino_genai.ModulePipeline(args.yaml)
    pipe.generate(image=load_image_as_ov_tensor(args.image), prompt=args.prompt)
    ov_text = str(pipe.get_output("generated_text"))

    ref_json = Path(args.report).with_suffix(".ref.json")
    cmd = [
        sys.executable,
        args.python_bridge,
        "--stage", "llm_full",
        "--model", args.hf_model,
        "--prompt", args.prompt,
        "--image", args.image,
        "--max-new-tokens", str(args.max_new_tokens),
        "--out", str(ref_json),
    ]
    subprocess.run(cmd, check=True)
    ref = json.loads(ref_json.read_text(encoding="utf-8"))
    py_text = ref["generated_text"]

    ov_n = norm_text(ov_text)
    py_n = norm_text(py_text)
    exact = ov_n == py_n
    contain = (ov_n in py_n) or (py_n in ov_n)

    report = {
        "ov_text": ov_text,
        "py_text": py_text,
        "exact_match": exact,
        "contains_match": contain,
        "pass": exact or contain,
    }
    Path(args.report).write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
'''


def write_file(path: Path, content: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if executable:
        mode = path.stat().st_mode
        path.chmod(mode | 0o111)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Qwen3.5 module YAML + skeletons + compare scripts")
    parser.add_argument("--python-model-file", required=True, help="Path to modeling_qwen3_5.py")
    parser.add_argument("--model-dir", required=True, help="OpenVINO model directory used in YAML")
    parser.add_argument("--output-dir", required=True, help="Directory to place generated artifacts")
    parser.add_argument("--gpu-policy", choices=["hybrid", "all-gpu", "all-cpu"], default="hybrid")
    parser.add_argument("--emit-cpu-compare-yaml", action="store_true", help="Also emit all-CPU YAML for baseline test")
    args = parser.parse_args()

    py_file = Path(args.python_model_file).resolve()
    out_dir = Path(args.output_dir).resolve()

    recovered_path = out_dir / "modeling_qwen3_5.recovered.py"
    analysis = analyze_python_model(py_file, recovered_path)

    devices = dict(DEFAULT_DEVICES)
    if args.gpu_policy == "all-gpu":
        for k in devices:
            devices[k] = "GPU"
    elif args.gpu_policy == "all-cpu":
        for k in devices:
            devices[k] = "CPU"

    yaml_gpu = build_yaml_content(args.model_dir, devices, cpu_compare=False)
    yaml_gpu_path = out_dir / "config.generated.gpu.yaml"
    write_file(yaml_gpu_path, yaml_gpu)

    yaml_cpu_path = None
    if args.emit_cpu_compare_yaml:
        yaml_cpu = build_yaml_content(args.model_dir, devices, cpu_compare=True)
        yaml_cpu_path = out_dir / "config.generated.cpu_compare.yaml"
        write_file(yaml_cpu_path, yaml_cpu)

    modules_dir = out_dir / "modules"
    for stage in [
        "image_preprocessor",
        "prompt_encoder",
        "text_embedding",
        "vision_encoder",
        "embedding_merger",
        "llm_inference",
    ]:
        base, hpp, cpp = generate_module_skeleton(stage, devices[stage])
        write_file(modules_dir / f"{base}.hpp", hpp)
        write_file(modules_dir / f"{base}.cpp", cpp)

    py_ref_dir = out_dir / "python_ref"
    write_file(py_ref_dir / "qwen3_5_reference_bridge.py", build_reference_bridge_script(), executable=True)
    write_file(py_ref_dir / "compare_pipeline_with_reference.py", build_compare_script(), executable=True)

    report = {
        "python_model_file": str(py_file),
        "source_mode": analysis.source_mode,
        "recovered_source_file": analysis.recovered_source_file,
        "classes_count": len(analysis.class_names),
        "functions_count": len(analysis.function_names),
        "signals": analysis.found_signals,
        "notes": analysis.notes,
        "generated": {
            "yaml_gpu": str(yaml_gpu_path),
            "yaml_cpu_compare": str(yaml_cpu_path) if yaml_cpu_path else None,
            "modules_dir": str(modules_dir),
            "python_ref_dir": str(py_ref_dir),
        },
    }
    write_file(out_dir / "analysis_report.json", json.dumps(report, ensure_ascii=False, indent=2))

    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
